apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-manager-api
  namespace: task-manager
spec:
  ingressClassName: nginx
  rules:
    - host: task-manager.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: task-manager-api
                port:
                  number: 8080
